
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-management-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      - DOCKER_ENV=true
    restart: unless-stopped
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: student-management-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: student-management-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data: