version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-management-backend-prod
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      - DOCKER_ENV=true
      - ENVIRONMENT=production
    restart: unless-stopped
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: student-management-frontend-prod
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: student-management-redis-prod
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: